src/main/java/br/com/casadocodigo/loja/models/CarrinhoCompras.java
package br.com.casadocodigo.loja.models;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Collection;
import java.util.LinkedHashMap;
import java.util.Map;

import org.springframework.context.annotation.Scope;
import org.springframework.context.annotation.ScopedProxyMode;
import org.springframework.stereotype.Component;
import org.springframework.web.context.WebApplicationContext;

@Component
@Scope(value=WebApplicationContext.SCOPE_SESSION, proxyMode=ScopedProxyMode.TARGET_CLASS) //Adiciona o carrinho ao escopo de sessao
//proxyMode faz o Spring cuidar dos conflitos de escopo, nao sendo necessario, por exemplo, especificar o escopo nos controllers
public class CarrinhoCompras implements Serializable { //Quando um objeto tem escopo de sessao é recomendado implementar a classe Serializable, para serializar o objeto ao guarda-lo na sessao
	
	private static final long serialVersionUID = 1L;
	
	private Map<CarrinhoItem, Integer> itens = new LinkedHashMap<CarrinhoItem, Integer>();
	
	public Collection<CarrinhoItem> getItens() {
		return itens.keySet();
	}
	
	public void add(CarrinhoItem item) {
		itens.put(item, getQuantidade(item) + 1);
	}

	public int getQuantidade(CarrinhoItem item) {
		if(!itens.containsKey(item))
			itens.put(item, 0);
		
		return itens.get(item);
	}
	
	public int getQuantidade() {
		return itens.values().stream().reduce(0, (proximo, acumulador) -> proximo + acumulador);
	}
	
	//Total de cada item
	public BigDecimal getTotal(CarrinhoItem item) {
		return item.getTotal(getQuantidade(item));
	}
	
	//Total geral
	public BigDecimal getTotal() {
		BigDecimal total = BigDecimal.ZERO;
		
		for(CarrinhoItem item : itens.keySet())
			total = total.add(getTotal(item));
		
		return total;
	}

	public void remover(Integer produtoId, TipoPreco tipoPreco) {
		Produto produto = new Produto();
		produto.setId(produtoId);
		
		itens.remove(new CarrinhoItem(produto, tipoPreco));
		
	}
}

src/main/java/br/com/casadocodigo/loja/controllers/HomeController.java
package br.com.casadocodigo.loja.controllers;

import java.util.Arrays;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.cache.annotation.Cacheable;
import org.springframework.stereotype.Controller;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.servlet.ModelAndView;

import br.com.casadocodigo.loja.daos.ProdutoDAO;
import br.com.casadocodigo.loja.daos.UsuarioDAO;
import br.com.casadocodigo.loja.models.Produto;
import br.com.casadocodigo.loja.models.Role;
import br.com.casadocodigo.loja.models.Usuario;

@Controller
public class HomeController {

	@Autowired
	private ProdutoDAO produtoDao;
	
	@Autowired
	private UsuarioDAO usuarioDao;
	
    @RequestMapping("/")
    @Cacheable(value="produtosHome") //Torna o metodo cacheavel, ou seja, o Spring faz a consulta ao banco apenas na primeira vez e armazena essas informações no cache
    public ModelAndView index(){
    	List<Produto> produtos = produtoDao.listar();
    	ModelAndView modelAndView = new ModelAndView("home");
    	modelAndView.addObject("produtos", produtos);
    	
    	return modelAndView;
    }
    
    //Metodo que insere o primeiro usuario para inicio da utilizacao do sistema (nao utilizar isso em producao, por questoes de seguranca)
    @Transactional //Torna o metodo transacional, para fazer transacoes com o bd
    @ResponseBody //Retorna a String como String mesmo, e nao uma jsp
    @RequestMapping("/url-magica-maluca-isdhiahfihtiuhuihbnigniusewr")
    public String urlMagicaMaluca() {
    	Usuario usuario = new Usuario();
    	usuario.setNome("Admin");
    	usuario.setEmail("admin@casadocodigo.com.br");
    	usuario.setSenha("$2a$04$qP517gz1KNVEJUTCkUQCY.JzEoXzHFjLAhPQjrg5iP6Z/UmWjvUhq");
    	usuario.setRoles(Arrays.asList(new Role("ROLE_ADMIN")));
    	
    	usuarioDao.gravar(usuario);
    	
    	return "Url Mágica executada";
    }
}

src/main/java/br/com/casadocodigo/loja/controllers/LoginController.java
package br.com.casadocodigo.loja.controllers;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@Controller
public class LoginController {

	@RequestMapping(value="/login", method=RequestMethod.GET)
	public String loginForm() {
		return "loginForm";
	}
}

src/main/webapp/WEB-INF/views/cabecalho.jsp
<%@ taglib uri="http://www.springframework.org/tags" prefix="s" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>
 
  <header id="layout-header">
		<div class="clearfix container">
			<a href="${s:mvcUrl('HC#index').build()}" id="logo">
			</a>
			<div id="header-content">
				<nav id="main-nav">
					
					<ul class="clearfix">
						<li>
							<a href="${s:mvcUrl('CCC#itens').build()}" rel="nofollow">
								<!-- Duas formas de exibir mensagem enviando parametros (com a tag fmt do JSTL ou com a tag do Spring)
									<fmt:message key="menu.carrinho" >
										<fmt:param value="${carrinhoCompras.quantidade}" />
									</fmt:message>
								-->
								<s:message code="menu.carrinho" arguments="${carrinhoCompras.quantidade}"></s:message>		
							</a>
						</li>
						<li>
							<a href="#" rel="nofollow">
								<fmt:message key="menu.sobre" />
							</a>
						</li>
						<li>
							<a href="?locale=pt_BR" rel="nofollow">
								<fmt:message key="menu.pt" />
							</a>
						</li>
						<li>
							<a href="?locale=en_US" rel="nofollow">
								<fmt:message key="menu.en" />
							</a>
						</li>
					</ul>
				</nav>
			</div>
		</div>
	</header>
	<nav class="categories-nav">
		<ul class="container">
			<li class="category"><a href="${s:mvcUrl('HC#index').build()}">
					<fmt:message key="navegacao.categoria.home" /> </a></li>
			<li class="category"><a href="#">
					<fmt:message key="navegacao.categoria.agile" /> </a></li>
			<li class="category"><a href="#">
					<fmt:message key="navegacao.categoria.front_end" /> </a></li>
			<li class="category"><a href="#">
					<fmt:message key="navegacao.categoria.games" /> </a></li>
			<li class="category"><a href="#">
					<fmt:message key="navegacao.categoria.java" /> </a></li>
			<li class="category"><a href="#">
					<fmt:message key="navegacao.categoria.mobile" /> </a></li>
			<li class="category"><a href="#"> 
					<fmt:message key="navegacao.categoria.web" /> </a></li>
			<li class="category"><a href="#"> 
					<fmt:message key="navegacao.categoria.outros" /> </a></li>
		</ul>
	</nav>

src/main/webapp/WEB-INF/views/error.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib tagdir="/WEB-INF/tags" prefix="tags" %> <!-- Tag de template criada manualmente -->
		
<tags:pageTemplate titulo="Erro genérico acontecendo" >
	<section id="index-section" class="container middle">
	
		<h2>Erro genérico acontecendo!</h2>
		
		<!-- Exibe o erro em um comentario. Caso seja necessario visualizar o que aconteceu, é só inspecionar o elemento e verificar o comentário
		
			Mensagem: ${exception.message} 
			<c:forEach items="${exception.stackTrace}" var="stk">
				${stk}
			</c:forEach>
		-->
		
	</section>
</tags:pageTemplate>

src/main/webapp/WEB-INF/views/home.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib uri="http://www.springframework.org/tags" prefix="s" %>
<%@ taglib uri="http://www.springframework.org/security/tags" prefix="security" %>
<%@ taglib tagdir="/WEB-INF/tags" prefix="tags" %> <!-- Tag de template criada manualmente -->
		
<tags:pageTemplate titulo="Livros de Java, Android, iOS, Mobile e muito mais..." >
	<section id="index-section" class="container middle">

		<h1 class="cdc-call">Últimos dias com os preços promocionais. Aproveite!</h1>
		<ul class="clearfix book-collection">

			<c:forEach items="${produtos}" var="produto">
				<li><a href="${s:mvcUrl('PC#detalhe').arg(0, produto.id).build()}" class="block clearfix">
						<h2 class="product-title">${produto.titulo}</h2>
						<img width="143"
							height="202"
							src="https://cdn.shopify.com/s/files/1/0155/7645/products/java8-featured_large.png?v=1411490181"
							alt="Java 8 Prático"
							title="Java 8 Prático"/>
						<small class="buy-button">Compre</small>
				</a></li>			
			</c:forEach>
			
		</ul>

		<h2 class="cdc-call">Diferenciais da Casa do Código</h2>

		<ul id="cdc-diferenciais" class="clearfix">
			<li class="col-left">
				<h3>E-books sem DRM. Leia onde quiser</h3>
				<p>
					<span class="sprite" id="sprite-drm"></span> Nossos e-books não
					possuem DRM, ou seja, você pode ler em qualquer computador, tablet
					e smartphone.
				</p>
			</li>
			<li class="col-right">
				<h3>Autores de renome na comunidade</h3>
				<p>
					<span class="sprite" id="sprite-renome"></span> Autores que
					participam ativamente na comunidade com Open Source, listas de
					discussão, grupos e mais.
				</p>
			</li>
			<li class="col-left">
				<h3>Receba atualizações dos e-books</h3>
				<p>
					<span class="sprite" id="sprite-atualizacoes"></span> Quando você
					compra um e-book, automaticamente tem direito às atualizações e
					correções dele.
				</p>
			</li>
			<li class="col-right">
				<h3>Livros com curadoria da Caelum</h3>
				<p>
					<span class="sprite" id="sprite-caelum"></span> Desenvolvedores
					experientes que avaliam e revisam os livros constantemente.
				</p>
			</li>
		</ul>
	</section>
</tags:pageTemplate>

src/main/webapp/WEB-INF/views/loginForm.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form" %>
<%@ taglib uri="http://www.springframework.org/tags" prefix="s" %>

<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>Livros de Java, Android, iPhone, Ruby, PHP e muito mais - Casa do Código</title>
	
		<c:url value="/resources/css" var="cssPath" />
		<link rel="stylesheet" href="${cssPath}/bootstrap.min.css" >
		<link rel="stylesheet" href="${cssPath}/bootstrap-theme.min.css" >
		
		<style type="text/css">
			body {
				padding: 60px 0px;
			}
		</style>
	</head>
	<body>
		<div class="container">
		
			<h1>Login da Casa do Código</h1>
			
			<!-- Action e campos do form estão com o padrao do Spring Security, pois ele é o responsavel por toda a parte de login -->
			<form:form servletRelativeAction="/login" method="POST">
				<div class="form-group">
					<label>E-mail</label>			
					<input name="username" class="form-control" />
				</div>
				<div class="form-group">
					<label>Senha</label>		
					<input type="password" name="password" class="form-control" />
				</div>
				<button type="submit" class="btn btn-primary">Logar</button>
			</form:form>
		</div>
	</body>
</html>